name: pmsn2020
description: "Proyectos de la materia `Programación Móvil y Servicios en la Nube`"
publish_to: 'none'

version: 2.0.0+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  toastification: ^3.0.3
  lottie: ^3.2.0
  dot_navigation_bar: ^1.0.2
  flutter_svg: ^2.2.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/icons/wuwa/
    - assets/images/wuwa/

  fonts:
    - family: Vikings
      fonts:
        - asset: fonts/vikings.ttf
